import type { Level } from "@prisma/client";

/**
 * DỮ LIỆU SEED — chỉnh sửa file này để cập nhật nội dung mẫu.
 *
 * Cấu trúc mỗi từ: [word, ipa, pos, định nghĩa (EN), câu ví dụ (EN), nghĩa tiếng Việt]
 * Mỗi cấp độ (beginner / middle / master) có 5 chủ đề, mỗi chủ đề 12 từ.
 *
 * Sau khi sửa, chạy lại:  npx prisma db seed
 * (seed sẽ XÓA toàn bộ dữ liệu cũ rồi nạp lại từ file này)
 */

export type SeedWord = [
  word: string,
  ipa: string,
  pos: string,
  def: string,
  ex: string,
  vi: string,
];

export type SeedTopic = {
  title: string;
  titleVi: string;
  level: Level;
  description: string;
  words: SeedWord[];
};

export const seedTopics: SeedTopic[] = [
  /* ============================================================
   * CẤP ĐỘ: CƠ BẢN (beginner) — 5 chủ đề
   * ============================================================ */
  {
    title: "Daily Activities",
    titleVi: "Hoạt động hằng ngày",
    level: "beginner",
    description: "Các động từ và cụm từ thông dụng cho sinh hoạt thường nhật.",
    words: [
      ["wake up", "/weɪk ʌp/", "verb", "To stop sleeping", "I wake up at 6 a.m. every day.", "thức dậy"],
      ["breakfast", "/ˈbrekfəst/", "noun", "The first meal of the day", "She eats breakfast before work.", "bữa sáng"],
      ["commute", "/kəˈmjuːt/", "verb", "To travel regularly to work", "He commutes by bus.", "đi làm (di chuyển)"],
      ["exercise", "/ˈeksəsaɪz/", "noun", "Physical activity to stay healthy", "Exercise keeps you fit.", "tập thể dục"],
      ["shower", "/ˈʃaʊə/", "noun", "Washing yourself under running water", "I take a shower every morning.", "tắm vòi sen"],
      ["lunch", "/lʌntʃ/", "noun", "A meal eaten in the middle of the day", "We had lunch together.", "bữa trưa"],
      ["nap", "/næp/", "noun", "A short sleep during the day", "A short nap boosts energy.", "giấc ngủ ngắn"],
      ["chore", "/tʃɔː/", "noun", "A routine task, especially at home", "Washing dishes is my least favorite chore.", "việc nhà"],
      ["schedule", "/ˈʃedjuːl/", "noun", "A plan of activities and times", "My schedule is full today.", "lịch trình"],
      ["habit", "/ˈhæbɪt/", "noun", "Something you do regularly", "Reading is a good habit.", "thói quen"],
      ["sleep", "/sliːp/", "verb", "To rest with eyes closed at night", "Children need to sleep early.", "ngủ"],
      ["dinner", "/ˈdɪnə/", "noun", "The main meal of the evening", "Dinner is ready at seven.", "bữa tối"],
    ],
  },
  {
    title: "Food & Drinks",
    titleVi: "Đồ ăn & Thức uống",
    level: "beginner",
    description: "Từ vựng cơ bản về món ăn, đồ uống và mùi vị.",
    words: [
      ["delicious", "/dɪˈlɪʃəs/", "adj", "Having a very pleasant taste", "This soup is delicious.", "ngon"],
      ["vegetable", "/ˈvedʒtəbl/", "noun", "A plant eaten as food", "Eat more vegetables.", "rau củ"],
      ["beverage", "/ˈbevərɪdʒ/", "noun", "Any type of drink", "Coffee is a popular beverage.", "đồ uống"],
      ["spicy", "/ˈspaɪsi/", "adj", "Having a strong hot flavor", "Thai food is often spicy.", "cay"],
      ["recipe", "/ˈresəpi/", "noun", "Instructions for cooking a dish", "She shared her cake recipe.", "công thức nấu ăn"],
      ["snack", "/snæk/", "noun", "A small amount of food between meals", "Fruit is a healthy snack.", "đồ ăn vặt"],
      ["sour", "/ˈsaʊə/", "adj", "Having a sharp acid taste", "Lemons are sour.", "chua"],
      ["grill", "/ɡrɪl/", "verb", "To cook over direct heat", "We grilled chicken last night.", "nướng"],
      ["ingredient", "/ɪnˈɡriːdiənt/", "noun", "One of the foods used to make a dish", "Mix all the ingredients well.", "nguyên liệu"],
      ["dessert", "/dɪˈzɜːt/", "noun", "Sweet food eaten after a meal", "Ice cream is my favorite dessert.", "món tráng miệng"],
      ["boil", "/bɔɪl/", "verb", "To cook in very hot water", "Boil the eggs for ten minutes.", "luộc"],
      ["fresh", "/freʃ/", "adj", "Recently made or picked, not old", "I bought fresh fish today.", "tươi"],
    ],
  },
  {
    title: "Family & Friends",
    titleVi: "Gia đình & Bạn bè",
    level: "beginner",
    description: "Từ vựng về các thành viên gia đình và những mối quan hệ thân thiết.",
    words: [
      ["parents", "/ˈpeərənts/", "noun", "Your mother and father", "My parents live in Hanoi.", "bố mẹ"],
      ["sibling", "/ˈsɪblɪŋ/", "noun", "A brother or sister", "I have two siblings.", "anh chị em ruột"],
      ["cousin", "/ˈkʌzn/", "noun", "A child of your uncle or aunt", "My cousin visits every summer.", "anh chị em họ"],
      ["grandparents", "/ˈɡrænpeərənts/", "noun", "The parents of your parents", "We visit our grandparents on weekends.", "ông bà"],
      ["neighbor", "/ˈneɪbə/", "noun", "A person living near you", "Our neighbor is very kind.", "hàng xóm"],
      ["friendship", "/ˈfrendʃɪp/", "noun", "The relationship between friends", "Their friendship has lasted thirty years.", "tình bạn"],
      ["relative", "/ˈrelətɪv/", "noun", "A member of your family", "Many relatives came to the wedding.", "họ hàng"],
      ["twin", "/twɪn/", "noun", "One of two children born together", "The twins look exactly alike.", "anh chị em sinh đôi"],
      ["marriage", "/ˈmærɪdʒ/", "noun", "The relationship of a married couple", "They have a happy marriage.", "hôn nhân"],
      ["nephew", "/ˈnefjuː/", "noun", "The son of your brother or sister", "My nephew is five years old.", "cháu trai"],
      ["niece", "/niːs/", "noun", "The daughter of your brother or sister", "His niece loves drawing.", "cháu gái"],
      ["close", "/kləʊs/", "adj", "Knowing someone very well", "We are close friends.", "thân thiết"],
    ],
  },
  {
    title: "Weather & Seasons",
    titleVi: "Thời tiết & Mùa",
    level: "beginner",
    description: "Miêu tả thời tiết, khí hậu và bốn mùa trong năm.",
    words: [
      ["sunny", "/ˈsʌni/", "adj", "Bright with sunshine", "It is sunny today.", "nắng"],
      ["rainy", "/ˈreɪni/", "adj", "Having a lot of rain", "The rainy season starts in May.", "mưa nhiều"],
      ["cloudy", "/ˈklaʊdi/", "adj", "Covered with clouds", "The sky is cloudy this morning.", "nhiều mây"],
      ["storm", "/stɔːm/", "noun", "Very bad weather with wind and rain", "The storm broke many trees.", "cơn bão"],
      ["temperature", "/ˈtemprətʃə/", "noun", "How hot or cold something is", "The temperature dropped at night.", "nhiệt độ"],
      ["forecast", "/ˈfɔːkɑːst/", "noun", "A report about future weather", "The forecast says rain tomorrow.", "dự báo thời tiết"],
      ["humid", "/ˈhjuːmɪd/", "adj", "Warm and slightly wet", "Summer here is very humid.", "oi bức, ẩm"],
      ["breeze", "/briːz/", "noun", "A light gentle wind", "A cool breeze came from the sea.", "gió nhẹ"],
      ["season", "/ˈsiːzn/", "noun", "One of the four parts of the year", "Autumn is my favorite season.", "mùa"],
      ["snow", "/snəʊ/", "noun", "Soft white frozen water", "Children love playing in the snow.", "tuyết"],
      ["thunder", "/ˈθʌndə/", "noun", "The loud sound during a storm", "Thunder scared the dog.", "sấm"],
      ["fog", "/fɒɡ/", "noun", "Thick cloud near the ground", "The fog made driving hard.", "sương mù"],
    ],
  },
  {
    title: "Animals",
    titleVi: "Động vật",
    level: "beginner",
    description: "Tên các loài vật quen thuộc trên cạn, dưới nước và trên trời.",
    words: [
      ["elephant", "/ˈelɪfənt/", "noun", "A very large animal with a trunk", "The elephant sprayed water with its trunk.", "con voi"],
      ["tiger", "/ˈtaɪɡə/", "noun", "A large wild cat with stripes", "Tigers live in the jungle.", "con hổ"],
      ["rabbit", "/ˈræbɪt/", "noun", "A small animal with long ears", "The rabbit eats carrots.", "con thỏ"],
      ["eagle", "/ˈiːɡl/", "noun", "A large strong bird that hunts", "An eagle flew over the mountain.", "đại bàng"],
      ["dolphin", "/ˈdɒlfɪn/", "noun", "A smart sea animal", "Dolphins swam beside our boat.", "cá heo"],
      ["snake", "/sneɪk/", "noun", "A long animal without legs", "A snake slid into the grass.", "con rắn"],
      ["sheep", "/ʃiːp/", "noun", "A farm animal kept for wool", "Sheep eat grass all day.", "con cừu"],
      ["frog", "/frɒɡ/", "noun", "A small jumping animal living near water", "The frog jumped into the pond.", "con ếch"],
      ["owl", "/aʊl/", "noun", "A bird that hunts at night", "An owl hooted in the dark.", "cú mèo"],
      ["bee", "/biː/", "noun", "An insect that makes honey", "Bees fly from flower to flower.", "con ong"],
      ["turtle", "/ˈtɜːtl/", "noun", "An animal with a hard shell", "The turtle moves slowly.", "con rùa"],
      ["whale", "/weɪl/", "noun", "The largest sea animal", "Whales sing under the sea.", "cá voi"],
    ],
  },

  /* ============================================================
   * CẤP ĐỘ: TRUNG CẤP (middle) — 5 chủ đề
   * ============================================================ */
  {
    title: "Business English",
    titleVi: "Tiếng Anh thương mại",
    level: "middle",
    description: "Từ vựng cho công việc văn phòng, họp hành và đàm phán.",
    words: [
      ["deadline", "/ˈdedlaɪn/", "noun", "The latest time something must be done", "The deadline is Friday.", "hạn chót"],
      ["negotiate", "/nɪˈɡəʊʃieɪt/", "verb", "To discuss to reach an agreement", "We negotiated a better price.", "đàm phán"],
      ["revenue", "/ˈrevənjuː/", "noun", "Money a company receives", "Revenue grew by 20%.", "doanh thu"],
      ["stakeholder", "/ˈsteɪkhəʊldə/", "noun", "A person with an interest in a business", "Inform all stakeholders.", "bên liên quan"],
      ["proposal", "/prəˈpəʊzl/", "noun", "A formal plan or suggestion", "The client approved our proposal.", "đề xuất"],
      ["budget", "/ˈbʌdʒɪt/", "noun", "Money available for a purpose", "We are over budget this month.", "ngân sách"],
      ["colleague", "/ˈkɒliːɡ/", "noun", "A person you work with", "My colleagues are friendly.", "đồng nghiệp"],
      ["agenda", "/əˈdʒendə/", "noun", "A list of items for a meeting", "What is on the agenda today?", "chương trình họp"],
      ["invoice", "/ˈɪnvɔɪs/", "noun", "A bill for goods or services", "Send the invoice to accounting.", "hóa đơn"],
      ["promotion", "/prəˈməʊʃn/", "noun", "A move to a higher position", "She got a promotion last year.", "thăng chức"],
      ["contract", "/ˈkɒntrækt/", "noun", "A legal written agreement", "Sign the contract here.", "hợp đồng"],
      ["profit", "/ˈprɒfɪt/", "noun", "Money gained after costs", "The company made a large profit.", "lợi nhuận"],
    ],
  },
  {
    title: "Travel & Transportation",
    titleVi: "Du lịch & Giao thông",
    level: "middle",
    description: "Từ vựng cho các chuyến đi, sân bay và phương tiện di chuyển.",
    words: [
      ["itinerary", "/aɪˈtɪnərəri/", "noun", "A detailed plan of a journey", "Our itinerary includes three cities.", "lịch trình chuyến đi"],
      ["departure", "/dɪˈpɑːtʃə/", "noun", "The act of leaving a place", "Check the departure time.", "khởi hành"],
      ["luggage", "/ˈlʌɡɪdʒ/", "noun", "Bags carried while traveling", "My luggage was lost at the airport.", "hành lý"],
      ["destination", "/ˌdestɪˈneɪʃn/", "noun", "The place you are going to", "Paris is a popular destination.", "điểm đến"],
      ["accommodation", "/əˌkɒməˈdeɪʃn/", "noun", "A place to stay", "The hotel offers cheap accommodation.", "chỗ ở"],
      ["passport", "/ˈpɑːspɔːt/", "noun", "An official travel document", "Show your passport at the gate.", "hộ chiếu"],
      ["delay", "/dɪˈleɪ/", "noun", "A period of waiting longer than planned", "The flight has a two-hour delay.", "sự trễ, hoãn"],
      ["sightseeing", "/ˈsaɪtsiːɪŋ/", "noun", "Visiting interesting places", "We went sightseeing downtown.", "tham quan"],
      ["fare", "/feə/", "noun", "Money paid for transport", "The bus fare is two dollars.", "tiền vé"],
      ["customs", "/ˈkʌstəmz/", "noun", "The airport area checking goods", "We passed through customs quickly.", "hải quan"],
      ["reservation", "/ˌrezəˈveɪʃn/", "noun", "An arrangement to keep a seat or room", "I made a reservation online.", "đặt chỗ"],
      ["souvenir", "/ˌsuːvəˈnɪə/", "noun", "A thing kept to remember a place", "She bought souvenirs for friends.", "quà lưu niệm"],
    ],
  },
  {
    title: "Health & Fitness",
    titleVi: "Sức khỏe & Thể chất",
    level: "middle",
    description: "Từ vựng về sức khỏe, luyện tập và khám chữa bệnh.",
    words: [
      ["nutrition", "/njuˈtrɪʃn/", "noun", "Food needed for health and growth", "Good nutrition builds strong bodies.", "dinh dưỡng"],
      ["injury", "/ˈɪndʒəri/", "noun", "Harm or damage to your body", "He recovered from his knee injury.", "chấn thương"],
      ["stamina", "/ˈstæmɪnə/", "noun", "Energy to keep going for a long time", "Running builds stamina.", "sức bền"],
      ["symptom", "/ˈsɪmptəm/", "noun", "A sign of illness", "Fever is a common symptom of flu.", "triệu chứng"],
      ["prescription", "/prɪˈskrɪpʃn/", "noun", "A doctor's order for medicine", "Take this prescription to the pharmacy.", "đơn thuốc"],
      ["recover", "/rɪˈkʌvə/", "verb", "To become healthy again", "She recovered after a week of rest.", "hồi phục"],
      ["balanced", "/ˈbælənst/", "adj", "Having the right amounts of everything", "Eat a balanced diet every day.", "cân bằng"],
      ["workout", "/ˈwɜːkaʊt/", "noun", "A session of physical exercise", "Morning workouts wake me up.", "buổi tập luyện"],
      ["immune", "/ɪˈmjuːn/", "adj", "Protected against a disease", "Vitamins support the immune system.", "miễn dịch"],
      ["checkup", "/ˈtʃekʌp/", "noun", "A general medical examination", "Get a health checkup every year.", "khám tổng quát"],
      ["allergy", "/ˈælədʒi/", "noun", "A bad reaction to certain foods or things", "He has a peanut allergy.", "dị ứng"],
      ["flexible", "/ˈfleksəbl/", "adj", "Able to bend and stretch easily", "Yoga makes your body flexible.", "dẻo dai"],
    ],
  },
  {
    title: "Education & Learning",
    titleVi: "Giáo dục & Học tập",
    level: "middle",
    description: "Từ vựng về trường lớp, thi cử và con đường học vấn.",
    words: [
      ["curriculum", "/kəˈrɪkjələm/", "noun", "The subjects taught at a school", "The curriculum includes art and music.", "chương trình học"],
      ["scholarship", "/ˈskɒləʃɪp/", "noun", "Money given to support study", "She won a full scholarship.", "học bổng"],
      ["assignment", "/əˈsaɪnmənt/", "noun", "A piece of work given to students", "Submit the assignment by Monday.", "bài tập được giao"],
      ["lecture", "/ˈlektʃə/", "noun", "A talk given to teach a group", "The lecture lasted an hour.", "bài giảng"],
      ["revise", "/rɪˈvaɪz/", "verb", "To study something again before a test", "Revise your notes tonight.", "ôn tập"],
      ["graduate", "/ˈɡrædʒueɪt/", "verb", "To finish school or university", "He graduated last June.", "tốt nghiệp"],
      ["tuition", "/tjuˈɪʃn/", "noun", "Money paid for being taught", "Tuition fees rise every year.", "học phí"],
      ["semester", "/sɪˈmestə/", "noun", "Half of a school year", "Final exams end the semester.", "học kỳ"],
      ["diploma", "/dɪˈpləʊmə/", "noun", "A certificate showing completed study", "She framed her diploma proudly.", "bằng cấp"],
      ["knowledge", "/ˈnɒlɪdʒ/", "noun", "Information and understanding", "Travel widens your knowledge.", "kiến thức"],
      ["concentrate", "/ˈkɒnsntreɪt/", "verb", "To focus all your attention", "I can't concentrate with this noise.", "tập trung"],
      ["literacy", "/ˈlɪtərəsi/", "noun", "The ability to read and write", "Literacy rates are rising worldwide.", "khả năng đọc viết"],
    ],
  },
  {
    title: "Shopping & Money",
    titleVi: "Mua sắm & Tiền bạc",
    level: "middle",
    description: "Từ vựng khi đi mua sắm, thanh toán và quản lý chi tiêu.",
    words: [
      ["bargain", "/ˈbɑːɡən/", "noun", "Something bought at a low price", "This coat was a real bargain.", "món hời"],
      ["discount", "/ˈdɪskaʊnt/", "noun", "A reduction in price", "Students get a 10% discount.", "giảm giá"],
      ["receipt", "/rɪˈsiːt/", "noun", "Paper proving you paid", "Keep the receipt for returns.", "hóa đơn mua hàng"],
      ["refund", "/ˈriːfʌnd/", "noun", "Money returned to you", "I asked for a full refund.", "hoàn tiền"],
      ["afford", "/əˈfɔːd/", "verb", "To have enough money for something", "I can't afford a new car now.", "đủ khả năng chi trả"],
      ["currency", "/ˈkʌrənsi/", "noun", "The money used in a country", "The local currency is the dong.", "tiền tệ"],
      ["expense", "/ɪkˈspens/", "noun", "Money spent on something", "Rent is my biggest expense.", "chi phí"],
      ["installment", "/ɪnˈstɔːlmənt/", "noun", "One of several regular payments", "Pay for the phone in six installments.", "trả góp"],
      ["warranty", "/ˈwɒrənti/", "noun", "A promise to repair a product", "The laptop has a two-year warranty.", "bảo hành"],
      ["counterfeit", "/ˈkaʊntəfɪt/", "adj", "Made to look like something real", "Beware of counterfeit goods online.", "giả mạo"],
      ["savings", "/ˈseɪvɪŋz/", "noun", "Money you have kept, not spent", "Her savings grew slowly but surely.", "tiền tiết kiệm"],
      ["purchase", "/ˈpɜːtʃəs/", "verb", "To buy something", "Purchase your tickets online.", "mua"],
    ],
  },

  /* ============================================================
   * CẤP ĐỘ: NÂNG CAO (master) — 5 chủ đề
   * ============================================================ */
  {
    title: "Academic Writing",
    titleVi: "Viết học thuật",
    level: "master",
    description: "Từ vựng nâng cao cho bài luận và nghiên cứu khoa học.",
    words: [
      ["hypothesis", "/haɪˈpɒθəsɪs/", "noun", "An idea tested by research", "The data supports our hypothesis.", "giả thuyết"],
      ["empirical", "/ɪmˈpɪrɪkl/", "adj", "Based on observation or experiment", "Empirical evidence is required.", "thực nghiệm"],
      ["synthesize", "/ˈsɪnθəsaɪz/", "verb", "To combine ideas into a whole", "Synthesize the findings of both studies.", "tổng hợp"],
      ["paradigm", "/ˈpærədaɪm/", "noun", "A typical model or framework", "This marks a paradigm shift.", "mô hình, hệ hình"],
      ["cite", "/saɪt/", "verb", "To refer to a source as evidence", "Always cite your sources.", "trích dẫn"],
      ["ambiguous", "/æmˈbɪɡjuəs/", "adj", "Having more than one meaning", "The phrase is ambiguous.", "mơ hồ"],
      ["methodology", "/ˌmeθəˈdɒlədʒi/", "noun", "A system of research methods", "Describe your methodology clearly.", "phương pháp luận"],
      ["coherent", "/kəʊˈhɪərənt/", "adj", "Logical and well organized", "Write a coherent argument.", "mạch lạc"],
      ["plagiarism", "/ˈpleɪdʒərɪzəm/", "noun", "Copying another's work as your own", "Plagiarism leads to expulsion.", "đạo văn"],
      ["refute", "/rɪˈfjuːt/", "verb", "To prove a statement wrong", "The study refutes earlier claims.", "bác bỏ"],
      ["implication", "/ˌɪmplɪˈkeɪʃn/", "noun", "A possible effect or result", "Discuss the implications of the result.", "hàm ý, hệ quả"],
      ["concise", "/kənˈsaɪs/", "adj", "Giving information clearly in few words", "Keep your abstract concise.", "súc tích"],
    ],
  },
  {
    title: "Technology & Innovation",
    titleVi: "Công nghệ & Đổi mới",
    level: "master",
    description: "Thuật ngữ nâng cao về công nghệ hiện đại.",
    words: [
      ["algorithm", "/ˈælɡərɪðəm/", "noun", "A set of rules for solving a problem", "The algorithm sorts data quickly.", "thuật toán"],
      ["breakthrough", "/ˈbreɪkθruː/", "noun", "An important discovery", "A breakthrough in battery design.", "đột phá"],
      ["obsolete", "/ˈɒbsəliːt/", "adj", "No longer used; out of date", "Fax machines are obsolete.", "lỗi thời"],
      ["scalable", "/ˈskeɪləbl/", "adj", "Able to grow without problems", "We need a scalable system.", "có khả năng mở rộng"],
      ["cybersecurity", "/ˌsaɪbəsɪˈkjʊərəti/", "noun", "Protection of computer systems", "Cybersecurity threats are rising.", "an ninh mạng"],
      ["automation", "/ˌɔːtəˈmeɪʃn/", "noun", "Use of machines instead of people", "Automation reduces manual work.", "tự động hóa"],
      ["prototype", "/ˈprəʊtətaɪp/", "noun", "A first model of a product", "We built a working prototype.", "bản mẫu"],
      ["disruptive", "/dɪsˈrʌptɪv/", "adj", "Changing an industry completely", "A disruptive technology emerged.", "mang tính đột phá"],
      ["bandwidth", "/ˈbændwɪdθ/", "noun", "Capacity of a network connection", "Video calls need more bandwidth.", "băng thông"],
      ["interface", "/ˈɪntəfeɪs/", "noun", "The way users interact with software", "The interface is intuitive.", "giao diện"],
      ["latency", "/ˈleɪtənsi/", "noun", "Delay before data transfer begins", "Low latency matters in gaming.", "độ trễ"],
      ["encryption", "/ɪnˈkrɪpʃn/", "noun", "Converting data into secret code", "Encryption protects your messages.", "mã hóa"],
    ],
  },
  {
    title: "Environment & Sustainability",
    titleVi: "Môi trường & Phát triển bền vững",
    level: "master",
    description: "Thuật ngữ về biến đổi khí hậu, bảo tồn và phát triển bền vững.",
    words: [
      ["sustainability", "/səˌsteɪnəˈbɪləti/", "noun", "Using resources without destroying them", "Sustainability guides our energy policy.", "tính bền vững"],
      ["emission", "/ɪˈmɪʃn/", "noun", "Gas sent out into the air", "We must cut carbon emissions by half.", "khí thải"],
      ["biodiversity", "/ˌbaɪəʊdaɪˈvɜːsəti/", "noun", "The variety of living things", "Rainforests are rich in biodiversity.", "đa dạng sinh học"],
      ["renewable", "/rɪˈnjuːəbl/", "adj", "Able to be replaced naturally", "Solar power is a renewable source.", "tái tạo được"],
      ["deforestation", "/ˌdiːˌfɒrɪˈsteɪʃn/", "noun", "The cutting down of forests", "Deforestation threatens wildlife.", "nạn phá rừng"],
      ["contaminate", "/kənˈtæmɪneɪt/", "verb", "To make dirty or poisonous", "Chemicals contaminated the river.", "làm ô nhiễm"],
      ["ecosystem", "/ˈiːkəʊsɪstəm/", "noun", "Living things and their environment", "Coral reefs are fragile ecosystems.", "hệ sinh thái"],
      ["conservation", "/ˌkɒnsəˈveɪʃn/", "noun", "The protection of nature", "Conservation saves endangered species.", "bảo tồn"],
      ["depletion", "/dɪˈpliːʃn/", "noun", "The reduction of something valuable", "Resource depletion worries scientists.", "sự cạn kiệt"],
      ["mitigate", "/ˈmɪtɪɡeɪt/", "verb", "To make something less severe", "Planting trees mitigates climate change.", "giảm nhẹ"],
      ["habitat", "/ˈhæbɪtæt/", "noun", "The natural home of an animal", "Pandas are losing their habitat.", "môi trường sống"],
      ["drought", "/draʊt/", "noun", "A long period without rain", "The drought ruined the harvest.", "hạn hán"],
    ],
  },
  {
    title: "Psychology & Behavior",
    titleVi: "Tâm lý học & Hành vi",
    level: "master",
    description: "Thuật ngữ về tư duy, cảm xúc và hành vi con người.",
    words: [
      ["cognition", "/kɒɡˈnɪʃn/", "noun", "The process of thinking and knowing", "Sleep strongly affects cognition.", "nhận thức"],
      ["bias", "/ˈbaɪəs/", "noun", "An unfair preference or dislike", "Avoid bias when hiring people.", "thiên kiến"],
      ["motivation", "/ˌməʊtɪˈveɪʃn/", "noun", "The reason for doing something", "Praise boosts students' motivation.", "động lực"],
      ["procrastinate", "/prəˈkræstɪneɪt/", "verb", "To delay doing what you should do", "Students procrastinate before exams.", "trì hoãn"],
      ["empathy", "/ˈempəθi/", "noun", "Understanding others' feelings", "Empathy builds strong teams.", "sự đồng cảm"],
      ["resilience", "/rɪˈzɪliəns/", "noun", "The ability to recover from difficulty", "Resilience helps in hard times.", "khả năng phục hồi"],
      ["subconscious", "/ˌsʌbˈkɒnʃəs/", "adj", "Existing below conscious awareness", "Habits form subconscious patterns.", "thuộc tiềm thức"],
      ["introvert", "/ˈɪntrəvɜːt/", "noun", "A quiet, inward-looking person", "Introverts recharge by being alone.", "người hướng nội"],
      ["perception", "/pəˈsepʃn/", "noun", "The way you notice and understand things", "Color changes our perception of taste.", "tri giác"],
      ["reinforce", "/ˌriːɪnˈfɔːs/", "verb", "To strengthen a behavior or idea", "Rewards reinforce good habits.", "củng cố"],
      ["anxiety", "/æŋˈzaɪəti/", "noun", "A feeling of worry or fear", "Exercise helps reduce anxiety.", "lo âu"],
      ["intuition", "/ˌɪntjuˈɪʃn/", "noun", "Knowing without conscious reasoning", "Trust your intuition sometimes.", "trực giác"],
    ],
  },
  {
    title: "Finance & Economics",
    titleVi: "Tài chính & Kinh tế",
    level: "master",
    description: "Thuật ngữ về đầu tư, ngân hàng và kinh tế vĩ mô.",
    words: [
      ["inflation", "/ɪnˈfleɪʃn/", "noun", "A general rise in prices", "Inflation hit 5% this year.", "lạm phát"],
      ["asset", "/ˈæset/", "noun", "Something valuable that you own", "Property is a stable asset.", "tài sản"],
      ["liability", "/ˌlaɪəˈbɪləti/", "noun", "Money that you owe", "List your assets and liabilities.", "khoản nợ phải trả"],
      ["dividend", "/ˈdɪvɪdend/", "noun", "Profit paid to shareholders", "The company raised its dividend.", "cổ tức"],
      ["portfolio", "/pɔːtˈfəʊliəʊ/", "noun", "A collection of investments", "Diversify your investment portfolio.", "danh mục đầu tư"],
      ["recession", "/rɪˈseʃn/", "noun", "A period of economic decline", "Many jobs vanish in a recession.", "suy thoái"],
      ["equity", "/ˈekwəti/", "noun", "The value of shares owned", "She holds equity in the startup.", "vốn chủ sở hữu"],
      ["collateral", "/kəˈlætərəl/", "noun", "Property promised for a loan", "The house serves as collateral.", "tài sản thế chấp"],
      ["volatile", "/ˈvɒlətaɪl/", "adj", "Changing quickly and unpredictably", "Crypto prices are highly volatile.", "biến động mạnh"],
      ["interest rate", "/ˈɪntrəst reɪt/", "noun", "The cost of borrowing money", "The bank cut interest rates again.", "lãi suất"],
      ["speculate", "/ˈspekjuleɪt/", "verb", "To invest with high risk for profit", "He speculates on gold prices.", "đầu cơ"],
      ["liquidity", "/lɪˈkwɪdəti/", "noun", "How easily assets become cash", "Cash offers maximum liquidity.", "tính thanh khoản"],
    ],
  },
];
